function dx = trig_dyn_toStop(tdummy,in2,udummy)
%TRIG_DYN_TOSTOP
%    DX = TRIG_DYN_TOSTOP(TDUMMY,IN2,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2021 04:37:51

cq = in2(1,:);
q_dot_0 = in2(4,:);
q_ddot = in2(3,:);
sq = in2(2,:);
t = in2(5,:);
t2 = q_dot_0.*2.0;
t4 = q_ddot./2.0;
t5 = t-1.0./2.0;
t3 = q_ddot+t2;
t6 = t3.*t5;
t7 = -t6;
t8 = q_dot_0+t4+t7;
dx = [-sq.*t8;cq.*t8;0.0;0.0;1.0];
